/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'CheckStateChange': EventHandler<{ key: string; expected: string }, never>
    'SetStateChange': EventHandler<{ message: string }, { topic: 'check-state-change'; data: { key: string; expected: string } }>
    'ApiTrigger': ApiRouteHandler<{ message: string }, ApiResponse<200, { message: string; traceId: string }>, { topic: 'test-state'; data: { message: string } }>
    'GSHDocumentQuery': ApiRouteHandler<{ query: string; documentType?: 'medical' | 'financial' | 'administrative' | 'regulatory' | 'all'; maxResults?: number; includeCodeContext?: boolean; complianceLevel?: 'HIPAA' | 'Healthcare' }, ApiResponse<200, { success: boolean; query: string; documentType: string; resultCount: number; totalResults: number; documents: unknown[]; complianceValidated: boolean; complianceLevel: string; timestamp: string; sessionId: string }> | ApiResponse<500, { success: boolean; error: string; details: string }>, never>
    'CodebaseAwareResearch': ApiRouteHandler<{ query: string; includeCodeContext?: boolean; includeGSHDocuments?: boolean; documentType?: 'medical' | 'financial' | 'administrative' | 'regulatory' | 'all'; maxDocuments?: number; researchFocus?: 'integration' | 'compliance' | 'implementation' | 'architecture' | 'general' }, ApiResponse<200, { success: boolean; query: string; researchFocus: string; documentContextUsed: boolean; documentCount: number; recommendations: string[]; implementationSteps: string[] }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'AnalyzeExistingCode': ApiRouteHandler<{ analysisType?: 'integration' | 'compliance' | 'architecture' | 'dependencies' | 'performance'; focusArea?: string; includeGSHContext?: boolean; maxDocuments?: number; codebaseAreas?: string[]; complianceLevel?: 'HIPAA' | 'Healthcare' | 'Standard' }, ApiResponse<200, { success: boolean; analysisType: string; focusArea: string; codebaseInsights: { architecture: string[]; dependencies: string[]; integrationPoints: string[]; complianceStatus: string }; recommendations: string[]; implementationPlan: { phases: { phase: number; tasks: string[]; estimatedTime: string }[]; priorities: string[]; risks: string[] }; gshDocumentContext: { relevantDocuments: unknown[]; complianceRequirements: string[]; integrationConsiderations: string[] } }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'EnhancedResearch': ApiRouteHandler<{ query: string; researchMode?: 'rag' | 'semantic_search' | 'memory_analysis' | 'comprehensive'; includeCloudRAG?: boolean; includeMemoryAnalysis?: boolean; includeSemanticSearch?: boolean; documentType?: 'medical' | 'financial' | 'administrative' | 'regulatory' | 'all'; maxDocuments?: number; contextWindow?: number; temperature?: number; complianceLevel?: 'HIPAA' | 'Healthcare' | 'Standard' }, ApiResponse<200, { success: boolean; query: string; researchMode: string; ragResponse?: { answer: string; sources: unknown[]; confidence: number }; semanticResults?: { documents: unknown[]; totalResults: number; queryTime: number }; memoryInsights?: { entities: unknown[]; relations: unknown[]; insights: string[] }; comprehensiveAnalysis: { synthesis: string; recommendations: string[]; actionItems: string[]; riskFactors: string[] }; metadata: { processingTime: number; sourcesUsed: number; complianceValidated: boolean } }> | ApiResponse<500, { success: boolean; error: string }>, never>
  }
}